name: firebase_dart_repo
repository: https://github.com/appsup-dart/firebase_dart

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  melos: ^7.0.0

workspace:
  - packages/firebase_dart
  - packages/firebase_dart_flutter
  - packages/firebase_dart_flutter_auth_google
  - packages/firebase_dart_flutter_auth_facebook
  - packages/firebase_dart_flutter_auth_apple
  - packages/firebase_dart_plus
  - packages/_integration_testing

melos:
  ide:
    intellij: false

  command:
    version:
      linkToCommits: true
      hooks: 
        pre:
          exec: |
            # Run serial tests in isolation (e.g. tests that access a remote database)
            # If the tests fail, exit with the code
            # If the tests pass, exit with 0
            # If there are no serial tests, exit with 0
            dart test -j 1 -t serial --fail-fast || exit_code=$?; if [[ $exit_code -eq 79 ]]; then exit 0; fi
            # Run non-serial tests in parallel
            dart test -x serial --fail-fast || exit_code=$?; if [[ $exit_code -eq 79 ]]; then exit 0; fi
          packageFilters:
            flutter: false
        preCommit:
          exec: "$PWD/remove-prereleases-from-changelog.sh"


  