import 'dart:convert';
import 'dart:io';

Future<void> main(List<String> args) async {
  var configPath = 'test/smoke/firebase-config.json';
  var runIo = true;
  var runChrome = true;

  for (var i = 0; i < args.length; i++) {
    switch (args[i]) {
      case '--config':
        if (i + 1 >= args.length) {
          _fail('Missing value for --config');
        }
        configPath = args[++i];
        break;
      case '--no-io':
        runIo = false;
        break;
      case '--no-chrome':
        runChrome = false;
        break;
      case '-h':
      case '--help':
        _printUsage();
        return;
      default:
        _fail('Unknown argument: ${args[i]}');
    }
  }

  var firebaseConfigJson = Platform.environment['FIREBASE_CONFIG_JSON'];
  if (firebaseConfigJson == null || firebaseConfigJson.isEmpty) {
    final file = File(configPath);
    if (!file.existsSync()) {
      _fail(
        'Missing Firebase config.\n\n'
        'Provide either:\n'
        '  1) FIREBASE_CONFIG_JSON env var, or\n'
        '  2) a JSON file at $configPath (override with --config).',
      );
    }
    firebaseConfigJson = file.readAsStringSync();
  }

  // Single-line JSON avoids fragile -D parsing when the file is pretty-printed.
  final firebaseConfig =
      json.decode(firebaseConfigJson) as Map<String, dynamic>;

  await _writeGeneratedConfig(firebaseConfig);

  const testFile = 'test/smoke';
  var dartArgs = ['test', '-t', 'smoke', '--run-skipped', testFile];

  if (runIo) {
    stdout.writeln('==> Running smoke tests on VM');
    await _runDart(dartArgs);
  }

  if (runChrome) {
    stdout.writeln('==> Running smoke tests on Chrome');
    final chromeArgs = <String>[
      ...dartArgs,
      '-p',
      'chrome',
      '--pause-after-load',
      '--concurrency=1'
    ];
    await _runDart(chromeArgs);
  }
}

Future<void> _writeGeneratedConfig(Map<String, dynamic> config) async {
  final dir = Directory('test/smoke/_generated');
  if (!dir.existsSync()) {
    dir.createSync(recursive: true);
  }
  final file = File('test/smoke/_generated/firebase_config.g.dart');
  final jsonConfig = const JsonEncoder.withIndent('  ').convert(config);
  await file.writeAsString(
    '// GENERATED by smoke/run.dart. Do not edit.\n'
    '// ignore_for_file: prefer_single_quotes\n'
    'const firebaseConfig = <String, dynamic>$jsonConfig;\n',
  );
}

Future<void> _runDart(List<String> args) async {
  // Use the same VM as this script. Spawning plain `dart` fails when it is not
  // on PATH (e.g. FVM shims, some IDE task environments).
  final process = await Process.start(
    Platform.resolvedExecutable,
    args,
    mode: ProcessStartMode.inheritStdio,
  );
  final exitCode = await process.exitCode;
  if (exitCode != 0) {
    exit(exitCode);
  }
}

Never _fail(String message) {
  stderr.writeln(message);
  stderr.writeln('');
  _printUsage();
  exit(1);
}

void _printUsage() {
  stderr.writeln('Usage: dart run smoke/run.dart [options]');
  stderr.writeln('');
  stderr.writeln('Options:');
  stderr.writeln(
      '  --config <path>  Path to firebase config json (default: smoke/firebase-config.json)');
  stderr.writeln('  --no-io          Skip VM smoke tests');
  stderr.writeln('  --no-chrome      Skip Chrome smoke tests');
  stderr.writeln('  --manual         Pause Chrome run for manual interaction');
  stderr.writeln('  -h, --help       Show this help');
}
