name: firebase_dart_flutter_auth_google
description: Provides a `firebase_dart` auth handler for sign in with Google using the native Google API
version: 0.1.0+2
homepage: https://github.com/appsup-dart/firebase_dart

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_dart: ^1.4.5
  google_sign_in: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
