name: Benchmark
on:
  push:
    branches:
      - master
      - develop

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run benchmark tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: appsup-dart/benchmark_test@action-v1
        with:
          working-directory: packages/firebase_dart
          paths: test/benchmark/
          compile: jit,aot,js,wasm
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-on-alert: true
          fail-on-alert: true
          sdk: flutter
