name: Benchmark
on:
  push:
    branches:
      - master
      - develop

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run benchmark tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - name: Run benchmark
        working-directory: packages/firebase_dart
        run: |
          set -o pipefail
          dart test --run-skipped -t benchmark test/benchmark | tee ../../benchmark_raw.txt
          perl -ne 'if (/(.+ x [0-9.,]+ ops\/sec ±[0-9.]+% \(\d+ runs sampled), average duration: [^)]+\)/) { print "$1)\n" }' ../../benchmark_raw.txt | tee ../../output.txt
          test -s ../../output.txt
      - name: Reset generated files
        run: git reset --hard HEAD
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'benchmarkjs'
          output-file-path: output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
